### PR TITLE
Create segregate_no.cpp

### PR DESCRIPTION
**Pull request by jyotika6221**
Program to segregate even and odd numbers in array.

### CODE REVIEW

**Comment by jyotika6221** [comment]
Please accept my pull request.

**Comment by AtharvaMahamuni** [comment]
Hello @jyotika6221,
I think the code which you contributed is similar to https://leetcode.com/problems/sort-array-by-parity/
I would suggest you make changes accordingly, explain the approach and add this link to your file.

**Comment by jyotika6221** [comment]
Hey, i request you to delete my file and my pull request.

**Comment by Jiganesh** [comment]
Yeah PR is closed

**Pull request closed without merging**
